### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by DfsDirect327** [VxKex/VxKex#1]
@vxiiduu1 
I assume you are the same person as the deleted @vxiiduu. What happened to [your user account](https://github.com/vxiiduu/) and [the  VxKex repository](https://github.com/vxiiduu/VxKex)? Have you got any email from GitHub about this? Is it true that Microsoft deleted your account?

The old VxKex repositority and your old GitHub user account disappeared few days ago without any prior notice.

**Comment by vxiiduu1** [comment]
Unfortunately i can't say anything but your guesses are very close to the truth.

**Comment by win98se** [comment]
Please also reinstate the NotepadEx repo. I have a mirror of it at https://codeberg.org/win98se/NotepadEx/src/commit/fa34e88ad6a6ffcd8df37aebefda51ece2b450b7 (cleaned up version at https://codeberg.org/win98se/NotepadEx, because you had two copies of source code in a single repo, so I've removed the older one), you can start from here.

**Comment by kuba2k2** [comment]
Unfortunately, he is most likely NOT the real vxiiduu, but a person trying to impersonate them. You can tell by the totally different style of the README and the sketchy part about BTC donation. It looks like they're just trying to make profit on someone else's work.

This is not ethical behavior and users should be aware that this is not the real/official repository nor GitHub account.

**Comment by tamr** [comment]
Can you comment on msfn.org leaving the link to this repo so we'd know it's the actual dev and not a third party malicious actor?
